# accounts page javascript files
---
- wesabe/views/pages/accounts.js
- wesabe/views/account-transactions.js
- wesabe/views/widgets/MoneyLabel.js
- wesabe/views/widgets/accounts/AccountWidget.js
- wesabe/views/widgets/accounts/AccountGroupList.js
- wesabe/views/widgets/accounts/AccountGroup.js
- wesabe/views/widgets/accounts/Account.js
- wesabe/views/widgets/accounts/Merchant.js
- wesabe/views/widgets/accounts/AutomaticUploaderErrorDialog.js
- wesabe/views/widgets/accounts/ManualUploadDialog.js
- wesabe/views/widgets/transactions/Transaction.js
- wesabe/views/widgets/trends-summary.js
- wesabe/views/widgets/tags/*.js
- wesabe/views/widgets/tags.js
- wesabe/views/widgets/export.js
- wesabe/views/shared/form.js
- wesabe/data/credentials/CredentialDataSource.js
- jquery.form.js
- jquery.history.js
- components/merchant-autocompleter.js
- processing.js
- wesabeCharts.js
- wesabe/date-range-picker.js
